version: "3.8"

services:
  formulario:
    build: .
    container_name: formulario-conversacional
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npx", "live-server", "--port=8080", "--host=0.0.0.0"]
